/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventana;

/**
 *
 * @author Pc
 */
public class VentanaClientes extends javax.swing.JFrame {

    /**
     * Creates new form VentanaClientes
     */
    public VentanaClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l_logo = new javax.swing.JLabel();
        b_volver = new javax.swing.JButton();
        b_salir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        b_buscar = new javax.swing.JButton();
        l_nombrecliente = new javax.swing.JLabel();
        l_idcliente1 = new javax.swing.JLabel();
        t_nombre = new javax.swing.JTextField();
        t_idcliente = new javax.swing.JTextField();
        b_borrar = new javax.swing.JButton();
        b_actualizar = new javax.swing.JButton();
        b_insertar = new javax.swing.JButton();
        l_nombremodulo = new javax.swing.JLabel();
        l_nombreapp = new javax.swing.JLabel();
        l_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_f.png"))); // NOI18N
        getContentPane().add(l_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, 70));

        b_volver.setBackground(new java.awt.Color(200, 200, 231));
        b_volver.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        b_volver.setForeground(new java.awt.Color(102, 0, 204));
        b_volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/volver.png"))); // NOI18N
        b_volver.setText(" Volver");
        b_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_volverActionPerformed(evt);
            }
        });
        getContentPane().add(b_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 120, 50));

        b_salir.setBackground(new java.awt.Color(200, 200, 231));
        b_salir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        b_salir.setForeground(new java.awt.Color(102, 0, 204));
        b_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        b_salir.setText(" Salir");
        getContentPane().add(b_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 530, 120, 50));

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 1000, 330));

        b_buscar.setBackground(new java.awt.Color(200, 200, 231));
        b_buscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_buscar.setForeground(new java.awt.Color(102, 0, 153));
        b_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        b_buscar.setText("  Buscar");
        getContentPane().add(b_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 130, 70));

        l_nombrecliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        l_nombrecliente.setForeground(new java.awt.Color(102, 0, 153));
        l_nombrecliente.setText("Nombre:");
        getContentPane().add(l_nombrecliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 150, 70, 30));

        l_idcliente1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        l_idcliente1.setForeground(new java.awt.Color(102, 0, 153));
        l_idcliente1.setText("Id Cliente:");
        getContentPane().add(l_idcliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 110, 70, 30));

        t_nombre.setBackground(new java.awt.Color(222, 222, 248));
        t_nombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(t_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 150, 210, 30));

        t_idcliente.setBackground(new java.awt.Color(222, 222, 248));
        t_idcliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        t_idcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_idclienteActionPerformed(evt);
            }
        });
        getContentPane().add(t_idcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 110, 210, 30));

        b_borrar.setBackground(new java.awt.Color(200, 200, 231));
        b_borrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_borrar.setForeground(new java.awt.Color(102, 0, 153));
        b_borrar.setText("Borrar");
        getContentPane().add(b_borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 100, 40));

        b_actualizar.setBackground(new java.awt.Color(200, 200, 231));
        b_actualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_actualizar.setForeground(new java.awt.Color(102, 0, 153));
        b_actualizar.setText("Actualizar");
        getContentPane().add(b_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 100, 40));

        b_insertar.setBackground(new java.awt.Color(200, 200, 231));
        b_insertar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_insertar.setForeground(new java.awt.Color(102, 0, 153));
        b_insertar.setText("Insertar");
        getContentPane().add(b_insertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 100, 40));

        l_nombremodulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        l_nombremodulo.setForeground(new java.awt.Color(102, 0, 153));
        l_nombremodulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_nombremodulo.setText("Módulo de Clientes");
        getContentPane().add(l_nombremodulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 1000, 70));

        l_nombreapp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        l_nombreapp.setText("Aplicación de Java © 2025");
        getContentPane().add(l_nombreapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 560, -1, -1));

        l_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_ppal.png"))); // NOI18N
        getContentPane().add(l_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1147, 619));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_volverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_volverActionPerformed

    private void t_idclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_idclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_idclienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_actualizar;
    private javax.swing.JButton b_borrar;
    private javax.swing.JButton b_buscar;
    private javax.swing.JButton b_insertar;
    private javax.swing.JButton b_salir;
    private javax.swing.JButton b_volver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l_fondo;
    private javax.swing.JLabel l_idcliente1;
    private javax.swing.JLabel l_logo;
    private javax.swing.JLabel l_nombreapp;
    private javax.swing.JLabel l_nombrecliente;
    private javax.swing.JLabel l_nombremodulo;
    private javax.swing.JTextField t_idcliente;
    private javax.swing.JTextField t_nombre;
    private javax.swing.JTable tabla1;
    // End of variables declaration//GEN-END:variables
}
